impl UniPass.enter_ability(nd: uni.Ability) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_arch_has(nd: uni.ArchHas) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_archetype(nd: uni.Archetype) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_assert_stmt(nd: uni.AssertStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_assign_compr(nd: uni.AssignCompr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_assignment(nd: uni.Assignment) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_atom_trailer(nd: uni.AtomTrailer) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_atom_unit(nd: uni.AtomUnit) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_await_expr(nd: uni.AwaitExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_awaiting_clause(nd: uni.AwaitingClause) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_binary_expr(nd: uni.BinaryExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_bool_expr(nd: uni.BoolExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_builtin_type(nd: uni.BuiltinType) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_cast_expr(nd: uni.CastExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_cfg_expr(nd: uni.CfgExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_client_block(nd: uni.ClientBlock) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_compare_expr(nd: uni.CompareExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_concurrent_expr(nd: uni.ConcurrentExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_connect_op(nd: uni.ConnectOp) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_ctrl_stmt(nd: uni.CtrlStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_delete_stmt(nd: uni.DeleteStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_dict_compr(nd: uni.DictCompr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_dict_val(nd: uni.DictVal) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_disconnect_op(nd: uni.DisconnectOp) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_disengage_stmt(nd: uni.DisengageStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_edge_op_ref(nd: uni.EdgeOpRef) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_edge_ref_trailer(nd: uni.EdgeRefTrailer) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_else_if(nd: uni.ElseIf) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_else_stmt(nd: uni.ElseStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_enum(nd: uni.Enum) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_event_signature(nd: uni.EventSignature) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_except(nd: uni.Except) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_expr_as_item(nd: uni.ExprAsItem) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_expr_stmt(nd: uni.ExprStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_f_string(nd: uni.FString) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_filter_compr(nd: uni.FilterCompr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_finally_stmt(nd: uni.FinallyStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_formatted_value(nd: uni.FormattedValue) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_func_call(nd: uni.FuncCall) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_func_signature(nd: uni.FuncSignature) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_gen_compr(nd: uni.GenCompr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_global_stmt(nd: uni.GlobalStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_global_vars(nd: uni.GlobalVars) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_has_var(nd: uni.HasVar) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_if_else_expr(nd: uni.IfElseExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_if_stmt(nd: uni.IfStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_impl_def(nd: uni.ImplDef) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_import(nd: uni.Import) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_in_for_stmt(nd: uni.InForStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_index_slice(nd: uni.IndexSlice) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_inner_compr(nd: uni.InnerCompr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_iter_for_stmt(nd: uni.IterForStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_attribute(nd: uni.JsxAttribute) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_child(nd: uni.JsxChild) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_comment(nd: uni.JsxComment) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_element(nd: uni.JsxElement) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_element_name(nd: uni.JsxElementName) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_expression(nd: uni.JsxExpression) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_normal_attribute(nd: uni.JsxNormalAttribute) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_slot(nd: uni.JsxSlot) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_spread_attribute(nd: uni.JsxSpreadAttribute) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_jsx_text(nd: uni.JsxText) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_k_v_pair(nd: uni.KVPair) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_k_w_pair(nd: uni.KWPair) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_lambda_expr(nd: uni.LambdaExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_list_compr(nd: uni.ListCompr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_list_val(nd: uni.ListVal) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_arch(nd: uni.MatchArch) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_as(nd: uni.MatchAs) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_case(nd: uni.MatchCase) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_k_v_pair(nd: uni.MatchKVPair) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_mapping(nd: uni.MatchMapping) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_or(nd: uni.MatchOr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_sequence(nd: uni.MatchSequence) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_singleton(nd: uni.MatchSingleton) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_star(nd: uni.MatchStar) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_stmt(nd: uni.MatchStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_value(nd: uni.MatchValue) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_match_wild(nd: uni.MatchWild) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_module(nd: uni.Module) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_module_code(nd: uni.ModuleCode) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_module_item(nd: uni.ModuleItem) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_module_path(nd: uni.ModulePath) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_multi_string(nd: uni.MultiString) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_name(nd: uni.Name) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_native_block(nd: uni.NativeBlock) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_non_local_stmt(nd: uni.NonLocalStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_param_var(nd: uni.ParamVar) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_py_inline_code(nd: uni.PyInlineCode) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_raise_stmt(nd: uni.RaiseStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_region_stmt(nd: uni.RegionStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_report_stmt(nd: uni.ReportStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_return_stmt(nd: uni.ReturnStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_sem_def(nd: uni.SemDef) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_server_block(nd: uni.ServerBlock) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_set_compr(nd: uni.SetCompr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_set_val(nd: uni.SetVal) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_slice(nd: uni.Slice) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_special_var_ref(nd: uni.SpecialVarRef) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_string(nd: uni.String) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_sub_tag(nd: uni.SubTag) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_switch_case(nd: uni.SwitchCase) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_switch_stmt(nd: uni.SwitchStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_test(nd: uni.Test) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_token(nd: uni.Token) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_try_stmt(nd: uni.TryStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_tuple_val(nd: uni.TupleVal) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_type_alias(nd: uni.TypeAlias) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_type_param(nd: uni.TypeParam) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_typed_ctx_block(nd: uni.TypedCtxBlock) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_unary_expr(nd: uni.UnaryExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_visit_stmt(nd: uni.VisitStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_while_stmt(nd: uni.WhileStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_forever_stmt(nd: uni.ForeverStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_with_stmt(nd: uni.WithStmt) -> None {
    self.default_enter(nd);
}

impl UniPass.enter_yield_expr(nd: uni.YieldExpr) -> None {
    self.default_enter(nd);
}

impl UniPass.exit_ability(nd: uni.Ability) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_arch_has(nd: uni.ArchHas) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_archetype(nd: uni.Archetype) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_assert_stmt(nd: uni.AssertStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_assign_compr(nd: uni.AssignCompr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_assignment(nd: uni.Assignment) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_atom_trailer(nd: uni.AtomTrailer) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_atom_unit(nd: uni.AtomUnit) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_await_expr(nd: uni.AwaitExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_awaiting_clause(nd: uni.AwaitingClause) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_binary_expr(nd: uni.BinaryExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_bool(nd: uni.Bool) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_bool_expr(nd: uni.BoolExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_builtin_type(nd: uni.BuiltinType) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_cast_expr(nd: uni.CastExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_cfg_expr(nd: uni.CfgExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_client_block(nd: uni.ClientBlock) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_comment_token(nd: uni.CommentToken) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_compare_expr(nd: uni.CompareExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_concurrent_expr(nd: uni.ConcurrentExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_connect_op(nd: uni.ConnectOp) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_ctrl_stmt(nd: uni.CtrlStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_delete_stmt(nd: uni.DeleteStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_dict_compr(nd: uni.DictCompr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_dict_val(nd: uni.DictVal) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_disconnect_op(nd: uni.DisconnectOp) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_disengage_stmt(nd: uni.DisengageStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_edge_op_ref(nd: uni.EdgeOpRef) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_edge_ref_trailer(nd: uni.EdgeRefTrailer) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_ellipsis(nd: uni.Ellipsis) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_else_if(nd: uni.ElseIf) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_else_stmt(nd: uni.ElseStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_enum(nd: uni.Enum) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_event_signature(nd: uni.EventSignature) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_except(nd: uni.Except) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_expr_as_item(nd: uni.ExprAsItem) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_expr_stmt(nd: uni.ExprStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_f_string(nd: uni.FString) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_filter_compr(nd: uni.FilterCompr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_finally_stmt(nd: uni.FinallyStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_float(nd: uni.Float) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_formatted_value(nd: uni.FormattedValue) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_func_call(nd: uni.FuncCall) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_func_signature(nd: uni.FuncSignature) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_gen_compr(nd: uni.GenCompr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_global_stmt(nd: uni.GlobalStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_global_vars(nd: uni.GlobalVars) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_has_var(nd: uni.HasVar) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_if_else_expr(nd: uni.IfElseExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_if_stmt(nd: uni.IfStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_impl_def(nd: uni.ImplDef) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_import(nd: uni.Import) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_in_for_stmt(nd: uni.InForStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_index_slice(nd: uni.IndexSlice) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_inner_compr(nd: uni.InnerCompr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_int(nd: uni.Int) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_iter_for_stmt(nd: uni.IterForStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_attribute(nd: uni.JsxAttribute) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_child(nd: uni.JsxChild) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_comment(nd: uni.JsxComment) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_element(nd: uni.JsxElement) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_element_name(nd: uni.JsxElementName) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_expression(nd: uni.JsxExpression) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_normal_attribute(nd: uni.JsxNormalAttribute) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_slot(nd: uni.JsxSlot) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_spread_attribute(nd: uni.JsxSpreadAttribute) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_jsx_text(nd: uni.JsxText) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_k_v_pair(nd: uni.KVPair) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_k_w_pair(nd: uni.KWPair) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_lambda_expr(nd: uni.LambdaExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_list_compr(nd: uni.ListCompr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_list_val(nd: uni.ListVal) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_arch(nd: uni.MatchArch) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_as(nd: uni.MatchAs) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_case(nd: uni.MatchCase) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_k_v_pair(nd: uni.MatchKVPair) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_mapping(nd: uni.MatchMapping) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_or(nd: uni.MatchOr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_sequence(nd: uni.MatchSequence) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_singleton(nd: uni.MatchSingleton) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_star(nd: uni.MatchStar) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_stmt(nd: uni.MatchStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_value(nd: uni.MatchValue) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_match_wild(nd: uni.MatchWild) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_module(nd: uni.Module) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_module_code(nd: uni.ModuleCode) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_module_item(nd: uni.ModuleItem) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_module_path(nd: uni.ModulePath) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_multi_string(nd: uni.MultiString) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_name(nd: uni.Name) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_native_block(nd: uni.NativeBlock) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_non_local_stmt(nd: uni.NonLocalStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_null(nd: uni.Null) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_param_var(nd: uni.ParamVar) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_py_inline_code(nd: uni.PyInlineCode) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_raise_stmt(nd: uni.RaiseStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_region_stmt(nd: uni.RegionStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_report_stmt(nd: uni.ReportStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_return_stmt(nd: uni.ReturnStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_sem_def(nd: uni.SemDef) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_semi(nd: uni.Semi) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_server_block(nd: uni.ServerBlock) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_set_compr(nd: uni.SetCompr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_set_val(nd: uni.SetVal) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_slice(nd: uni.Slice) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_special_var_ref(nd: uni.SpecialVarRef) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_string(nd: uni.String) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_sub_tag(nd: uni.SubTag) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_switch_case(nd: uni.SwitchCase) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_switch_stmt(nd: uni.SwitchStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_test(nd: uni.Test) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_token(nd: uni.Token) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_try_stmt(nd: uni.TryStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_tuple_val(nd: uni.TupleVal) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_type_alias(nd: uni.TypeAlias) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_type_param(nd: uni.TypeParam) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_typed_ctx_block(nd: uni.TypedCtxBlock) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_unary_expr(nd: uni.UnaryExpr) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_visit_stmt(nd: uni.VisitStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_while_stmt(nd: uni.WhileStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_forever_stmt(nd: uni.ForeverStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_with_stmt(nd: uni.WithStmt) -> None {
    self.default_exit(nd);
}

impl UniPass.exit_yield_expr(nd: uni.YieldExpr) -> None {
    self.default_exit(nd);
}
