name: Release jac-super to PYPI

on: workflow_dispatch

jobs:
  release-super:
    name: Release
    runs-on: blacksmith-4vcpu-ubuntu-2404
    defaults:
      run:
        working-directory: jac-super

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Python 3.12, 3.13, 3.14
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.12
            3.13
            3.14

      - name: Install jaclang and twine
        run: |
          pip install -e ../jac
          pip install twine

      - name: Build and publish
        run: |
          jac bundle --precompile
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
